# Generated by Django 3.1.5 on 2021-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
