# Generated by Django 3.1.5 on 2021-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notesinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesinfo',
            name='date',
            field=models.DateField(default='00-00-00', null=True),
        ),
    ]
